excluded:
  - Carthage
  - Pods
force_cast: error
force_try:
  severity: error 
line_length: 140
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 300
  error: 500
type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length: 
    error: 2
reporter: "xcode" 
