excluded:
  - Carthage
  - Pods
disabled_rules:
  - trailing_whitespace
force_cast: warning 
force_try:
  severity: warning 
line_length:
  ignores_comments: true
  ignores_urls: true
  warning: 140
ignores_comments: true
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 1 # only error
    warning: 1
  excluded: # excluded via string array
    - id
